//! Integration tests for querying a local icechunk store from SQL (feature `icechunk`).
//!
//! Drives the real `CREATE EXTERNAL TABLE ... STORED AS ZARR` path through
//! `ZarrTableFactory`, exactly as the CLI does, against `data/synthetic.icechunk`
//! (generated by `scripts/gen_synthetic_icechunk.py`; the M1 fixture:
//! `temperature[t,y,x] = t*100 + y*10 + x`, coords time(7)/lat(10)/lon(10)).
//!
//! Run: `cargo test --features icechunk --test integration_icechunk`
#![cfg(feature = "icechunk")]

use std::sync::Arc;

use datafusion::execution::session_state::SessionStateBuilder;
use datafusion::prelude::SessionContext;
use zarr_datafusion::datasource::factory::ZarrTableFactory;
use zarr_datafusion::optimizer::{CountStatisticsRule, MinMaxStatisticsRule};

const STORE: &str = "data/synthetic.icechunk";

/// A SessionContext wired like the CLI: ZARR table factory + the stat optimizer rules.
fn ctx() -> SessionContext {
    let state = SessionStateBuilder::new()
        .with_default_features()
        .with_table_factory("ZARR".to_string(), Arc::new(ZarrTableFactory) as _)
        .with_optimizer_rule(Arc::new(CountStatisticsRule::new()))
        .with_optimizer_rule(Arc::new(MinMaxStatisticsRule::new()))
        .build();
    SessionContext::new_with_state(state)
}

async fn register(ctx: &SessionContext) {
    ctx.sql(&format!(
        "CREATE EXTERNAL TABLE syn STORED AS ZARR LOCATION '{STORE}'"
    ))
    .await
    .expect("CREATE EXTERNAL TABLE over icechunk store")
    .collect()
    .await
    .expect("execute CREATE");
}

/// A single scalar cell from a one-row, one-column result.
async fn scalar_i64(ctx: &SessionContext, sql: &str) -> i64 {
    let batches = ctx.sql(sql).await.unwrap().collect().await.unwrap();
    let b = &batches[0];
    let col = b.column(0);
    // COUNT/aggregates may come back as Int64; coerce via display for robustness.
    let arr = arrow::compute::cast(col, &arrow::datatypes::DataType::Int64).unwrap();
    let arr = arr
        .as_any()
        .downcast_ref::<arrow::array::Int64Array>()
        .unwrap();
    arr.value(0)
}

#[tokio::test]
async fn schema_has_expected_columns() {
    let ctx = ctx();
    register(&ctx).await;

    let df = ctx.sql("SELECT * FROM syn LIMIT 0").await.unwrap();
    let names: Vec<String> = df
        .schema()
        .fields()
        .iter()
        .map(|f| f.name().clone())
        .collect();
    for expected in ["time", "lat", "lon", "temperature"] {
        assert!(
            names.iter().any(|n| n == expected),
            "expected column '{expected}' in {names:?}"
        );
    }
}

#[tokio::test]
async fn count_matches_cartesian_product() {
    let ctx = ctx();
    register(&ctx).await;
    // 7 time × 10 lat × 10 lon = 700 rows.
    assert_eq!(scalar_i64(&ctx, "SELECT COUNT(*) FROM syn").await, 700);
}

#[tokio::test]
async fn min_max_temperature() {
    let ctx = ctx();
    register(&ctx).await;
    // temperature = t*100 + y*10 + x, so min=0 (0,0,0), max=699 (6,9,9).
    let batches = ctx
        .sql("SELECT MIN(temperature) AS mn, MAX(temperature) AS mx FROM syn")
        .await
        .unwrap()
        .collect()
        .await
        .unwrap();
    let b = &batches[0];
    let mn = b
        .column(0)
        .as_any()
        .downcast_ref::<arrow::array::Float64Array>()
        .unwrap()
        .value(0);
    let mx = b
        .column(1)
        .as_any()
        .downcast_ref::<arrow::array::Float64Array>()
        .unwrap()
        .value(0);
    assert_eq!(mn, 0.0);
    assert_eq!(mx, 699.0);
}

#[tokio::test]
async fn value_exact_at_coordinate() {
    let ctx = ctx();
    register(&ctx).await;
    // Pin one cell by its COORDINATE VALUES (not indices): the generator writes
    // time = arange(7) (so time index 3 -> value 3), lat = linspace(-90,90,10)
    // (index 4 -> -10.0), lon = linspace(0,360,10,endpoint=False) (index 5 -> 180.0).
    // That cell is temperature[3,4,5] = 3*100 + 4*10 + 5 = 345.
    let batches = ctx
        .sql("SELECT temperature FROM syn WHERE time = 3 AND lat = -10.0 AND lon = 180.0")
        .await
        .unwrap()
        .collect()
        .await
        .unwrap();
    let total: usize = batches.iter().map(|b| b.num_rows()).sum();
    assert_eq!(total, 1, "expected exactly one matching row");
    let v = batches
        .iter()
        .find(|b| b.num_rows() > 0)
        .unwrap()
        .column(0)
        .as_any()
        .downcast_ref::<arrow::array::Float64Array>()
        .unwrap()
        .value(0);
    assert_eq!(v, 345.0);
}
