//! Example: Query synthetic weather data using SQL
//!
//! This example demonstrates querying the synthetic weather dataset
//! generated by `scripts/data_gen.py`. The data contains random
//! temperature and humidity values for a 10x10 lat/lon grid over 7 days.
//!
//! Run with tracing enabled:
//!   RUST_LOG=info cargo run --example query_synthetic
//!   RUST_LOG=debug cargo run --example query_synthetic

use std::sync::Arc;

use datafusion::prelude::SessionContext;
use tracing_subscriber::EnvFilter;
use zarr_datafusion::datasource::zarr::ZarrTable;
use zarr_datafusion::reader::schema_inference::infer_schema;

async fn run_query(
    ctx: &SessionContext,
    description: &str,
    sql: &str,
) -> datafusion::error::Result<()> {
    println!("\n{description}");
    println!("SQL: {sql}");
    println!();
    let df = ctx.sql(sql).await?;
    df.show().await?;
    Ok(())
}

#[tokio::main]
async fn main() -> datafusion::error::Result<()> {
    // Initialize tracing subscriber
    tracing_subscriber::fmt()
        .with_env_filter(EnvFilter::from_default_env())
        .with_target(true)
        .with_line_number(true)
        .init();

    let ctx = SessionContext::new();

    // Load synthetic weather data (Zarr v3)
    let store_path = "data/synthetic_v3.zarr";
    let schema = Arc::new(infer_schema(store_path).expect("Failed to infer schema"));

    println!("Synthetic Weather Data Schema:");
    for field in schema.fields() {
        println!("  {}: {:?}", field.name(), field.data_type());
    }

    let table = Arc::new(ZarrTable::new(schema, store_path));
    ctx.register_table("synthetic", table)?;

    run_query(
        &ctx,
        "Sample data (first 10 rows):",
        "SELECT * FROM synthetic LIMIT 10",
    )
    .await?;

    run_query(
        &ctx,
        "Filtered data (temperature > 5):",
        "SELECT time, lat, lon, temperature FROM synthetic WHERE temperature > 5 LIMIT 10",
    )
    .await?;

    run_query(
        &ctx,
        "Average temperature per day:",
        "SELECT time, AVG(temperature) as avg_temp FROM synthetic GROUP BY time ORDER BY time",
    )
    .await?;

    run_query(
        &ctx,
        "Total rows:",
        "SELECT COUNT(temperature) as total FROM synthetic",
    )
    .await?;

    Ok(())
}
